- name: Disabling NodeJS Default Version
  ansible.builtin.shell: dnf module disable nodejs -y


- name: Enabling the Required NodeJS Version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Installing the NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Copying the Backend Service
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding Application user
  ansible.builtin.user:
    name: expense

- name: Import Common Role-App Preq
  ansible.builtin.import_role:
    name: common
    tasks_from: app-preq
  vars:
     app_dir: /app
     component: backend

- name: Downloading the NodeJS Dependencies
  ansible.builtin.shell: npm install
  args :
    chdir: /app #chdir is used  to extract the download content to specific Directory

- name: Install MysSQL Client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name:  To Load the Schema
  ansible.builtin.shell: mysql -h mysql-{{env}}.kgsdevops.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql

- name:  Starting Backend Service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes
