- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy the Expense Content
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role-App Preq
  ansible.builtin.import_role:
    name: common
    tasks_from: app_preq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: Starting nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes